import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Notifications } from "@mantine/notifications";

const inter = Inter({ subsets: ["latin"] });
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { TopHeader } from "@/features/Home/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <Notifications />
          <TopHeader />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
