export enum APP {
  NAME = "project-tokowaifu",
  DESCRIPTION = "Generated by create next app",
}

export enum COOKIE_NAME {
  AUTH = "Authorization"
}

export enum HEADER_NAME {
  USER_ID = "user-id"
}
export enum COMMAND {
  REFETCH = "REFETCH",
  FETCH = "FETCH",
  SEARCH = "SEARCH"
}